version: '3.8'

services:
  users_service:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    restart: always
    depends_on:
      - users_service_database
    volumes:
      - ./:/app

  users_service_database:
    image: mongo:6.0.9
    restart: always
    # TODO: Remove after deploy
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data_volume:/data/db
volumes:
  mongodb_data_volume:
